---
title: "Reproducible document"
author: "Mette BI"
format: html
---

## Basics of R

```{r}
1 + 1
```

## setup code chunk

```{r setup}
#| message: false
#| warning: false
library(tidyverse)
post_meal_data <- read_csv2(here::here("data/post-meal-insulin.csv"))
```

## Showing the data

```{r}
post_meal_data
```

```{r}
glimpse(post_meal_data)
```

```{r}
ggplot(post_meal_data, aes(x = BMI)) +
  geom_histogram()
```

```{r}
#| fig-cap: "Distribution of BMI"
#| label: fig-mettes-histo
ggplot(post_meal_data, aes(x = BMI)) +
  geom_histogram()
```

@fig-mettes-histo

## Discrete plots

```{r}
#| fig-cap: "Group"
#| label: fig-group-discrete
ggplot(post_meal_data, aes(x = Group)) +
  geom_bar()
```

See @fig-group-discrete above for a cool plot!

```{r}
post_meal_data |>
  ggplot(aes(x = Group, fill = as.character(glykemi))) +
  geom_bar(position = position_dodge())
```
## putting two plots side by side

```{r}
ggplot(post_meal_data, aes(x = BMI)) +
  geom_histogram()
```

```{r}
post_meal_data |>
  ggplot(aes(x = Group, fill = as.character(glykemi))) +
  geom_bar()
```

```{r side-by-side-figs}
#| label: fig-bmi-glycemi
#| fig-cap: "BMI and glycemia, side by side"
#| fig-subcap:
#| - "Distribution of BMI"
#| - "Distribution of glycemia"
#| layout-ncol: 2

ggplot(post_meal_data, aes(x = BMI)) +
  geom_histogram()

post_meal_data |>
  ggplot(aes(x = Group, fill = as.character(glykemi))) +
  geom_bar()
```

```{r side-by-side-figs}
#| label: fig-bmi-glycemia
#| fig-cap: "BMI and glycemia, side by side"
#| fig-subcap:
#| - ""
#| - ""
#| layout-ncol: 2

ggplot(post_meal_data, aes(x = BMI)) +
  geom_histogram()

post_meal_data |>
  ggplot(aes(x = Group, fill = as.character(glykemi))) +
  geom_bar()
```

## Plotting two continuous variables

```{r}
#| fig-cap: "Scatterplot of BMI and the AUC for glucose"
#| label: fig-bmi-auc_pg
ggplot(post_meal_data, aes(x = BMI, y = auc_pg)) +
  geom_point() +
  geom_smooth()
```

## Pushing changes to remote aka github

## Pulling changes locally

## How I accessed Github from R and pushed the project to Github

look at 9 in the pre-course material https://guides.rostools.org/connect-github.html

